version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    restart: always
    environment:
      MINIO_ACCESS_KEY: your_access_key
      MINIO_SECRET_KEY: your_secret_key
    ports:
      - 9000:9000
    volumes:
      - minio_data:/data

volumes:
  db_data:
  minio_data:
