services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ark
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: notsecure
    ports:
      - '5432:5432'
    volumes:
      - .data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
